type = "matrix"

[[rules]]
principal = "nuon::sandbox"
operation = "provision"
role      = "{{.nuon.install.id}}-sandbox-provision"

[[rules]]
principal = "nuon::sandbox"
operation = "reprovision"
role      = "{{.nuon.install.id}}-sandbox-maintenance"

[[rules]]
principal = "nuon::sandbox"
operation = "deprovision"
role      = "{{.nuon.install.id}}-sandbox-deprovision"

[[rules]]
principal = "nuon::component:whoami"
operation = "deploy"
role      = "{{.nuon.install.id}}-whoami-deploy"

[[rules]]
principal = "nuon::component:whoami"
operation = "teardown"
role      = "{{.nuon.install.id}}-whoami-teardown"

[[rules]]
principal = "nuon::component:certificate"
operation = "deploy"
role      = "{{.nuon.install.id}}-certificate-deploy"

[[rules]]
principal = "nuon::component:certificate"
operation = "teardown"
role      = "{{.nuon.install.id}}-certificate-teardown"

[[rules]]
principal = "nuon::action:deployments_status"
operation = "trigger"
role      = "{{.nuon.install.id}}-deployments-status-trigger"

[[rules]]
principal = "nuon::action:deployment_restart"
operation = "trigger"
role      = "{{.nuon.install.id}}-deployment-restart-trigger"
